# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-24 23:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=100)),
                ('context', models.TextField()),
                ('publish_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Studentity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('field_of_study', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SuperConductor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='xnote_base.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('superconductor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='xnote_base.SuperConductor')),
                ('national_id', models.CharField(blank=True, max_length=100, null=True)),
                ('sharif_mail_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_image')),
            ],
            bases=('xnote_base.superconductor',),
        ),
        migrations.CreateModel(
            name='SuperInstitution',
            fields=[
                ('superconductor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='xnote_base.SuperConductor')),
                ('name', models.CharField(max_length=100)),
                ('is_formal', models.BooleanField(default=False)),
            ],
            bases=('xnote_base.superconductor',),
        ),
        migrations.AddField(
            model_name='follow',
            name='followed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follows', to='xnote_base.SuperConductor'),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('superinstitution_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='xnote_base.SuperInstitution')),
            ],
            bases=('xnote_base.superinstitution',),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('superinstitution_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='xnote_base.SuperInstitution')),
                ('is_department_group', models.BooleanField(default=False)),
            ],
            bases=('xnote_base.superinstitution',),
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('superinstitution_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='xnote_base.SuperInstitution')),
            ],
            bases=('xnote_base.superinstitution',),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set([('name',)]),
        ),
        migrations.AddField(
            model_name='superinstitution',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, to='xnote_base.Person'),
        ),
        migrations.AddField(
            model_name='studentity',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xnote_base.Person'),
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xnote_base.Person'),
        ),
        migrations.AddField(
            model_name='person',
            name='follows',
            field=models.ManyToManyField(related_name='following', through='xnote_base.Follow', to='xnote_base.SuperConductor'),
        ),
        migrations.AddField(
            model_name='person',
            name='interested_tags',
            field=models.ManyToManyField(blank=True, to='xnote_base.Tag'),
        ),
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='follow',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xnote_base.Person'),
        ),
        migrations.AddField(
            model_name='studentity',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xnote_base.Department'),
        ),
        migrations.AddField(
            model_name='group',
            name='related_university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xnote_base_group_related', to='xnote_base.University'),
        ),
        migrations.AddField(
            model_name='department',
            name='related_university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xnote_base.University'),
        ),
    ]
