# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.9 on 2016-02-29 06:43
=======
>>>>>>> origin/master
from __future__ import unicode_literals

from django.db import models, migrations
import django.utils.timezone
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
<<<<<<< HEAD
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
=======
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
>>>>>>> origin/master
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('follow_time', models.DateTimeField(default=django.utils.timezone.now, null=True, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('permissions', models.ManyToManyField(related_name='related_portfolios', to='xnote_base.Permission')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions', models.ManyToManyField(related_name='related_portfolios', to='xnote_base.Permission')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('is_public', models.BooleanField(default=False)),
<<<<<<< HEAD
                ('post_type', models.CharField(choices=[('normal', 'Normal'), ('quick', 'Quick')], default='normal', max_length=50)),
=======
                ('post_type', models.CharField(default=b'normal', max_length=50, choices=[(b'normal', b'Normal'), (b'quick', b'Quick')])),
>>>>>>> origin/master
                ('title', models.CharField(max_length=100)),
                ('context', models.TextField()),
                ('publish_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Studentity',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('student_id', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('field_of_study', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SuperConductor',
            fields=[
<<<<<<< HEAD
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(default='Unknown', max_length=100)),
                ('description', models.CharField(default='Nothing', max_length=1000)),
                ('url_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_formal', models.BooleanField(default=False)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_image')),
=======
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('real_name', models.CharField(default=b'Unknown', max_length=100)),
                ('description', models.CharField(default=b'Nothing', max_length=1000)),
                ('url_name', models.CharField(max_length=100, null=True, blank=True)),
                ('is_formal', models.BooleanField(default=False)),
                ('profile_image', models.ImageField(null=True, upload_to=b'profile_image', blank=True)),
>>>>>>> origin/master
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('parent', models.ForeignKey(related_name='children', blank=True, to='xnote_base.Tag', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
<<<<<<< HEAD
                ('superconductor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='xnote_base.SuperConductor')),
                ('national_id', models.CharField(blank=True, max_length=100, null=True)),
                ('sharif_mail_address', models.EmailField(blank=True, max_length=254, null=True)),
=======
                ('superconductor_ptr', models.OneToOneField(parent_link=True, auto_created=True, primary_key=True, serialize=False, to='xnote_base.SuperConductor')),
                ('national_id', models.CharField(max_length=100, null=True, blank=True)),
                ('sharif_mail_address', models.EmailField(max_length=254, null=True, blank=True)),
>>>>>>> origin/master
            ],
            bases=('xnote_base.superconductor',),
        ),
        migrations.CreateModel(
            name='SuperInstitution',
            fields=[
                ('superconductor_ptr', models.OneToOneField(parent_link=True, auto_created=True, primary_key=True, serialize=False, to='xnote_base.SuperConductor')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=('xnote_base.superconductor',),
        ),
        migrations.AddField(
            model_name='post',
            name='author',
<<<<<<< HEAD
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xnote_base.SuperConductor'),
=======
            field=models.ForeignKey(blank=True, to='xnote_base.SuperConductor', null=True),
>>>>>>> origin/master
        ),
        migrations.AddField(
            model_name='post',
            name='event',
<<<<<<< HEAD
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xnote_base.Event'),
=======
            field=models.ForeignKey(blank=True, to='xnote_base.Event', null=True),
>>>>>>> origin/master
        ),
        migrations.AddField(
            model_name='post',
            name='related_tags',
<<<<<<< HEAD
            field=models.ManyToManyField(blank=True, to='xnote_base.Tag'),
        ),
        migrations.AddField(
            model_name='membership',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_obj', to='xnote_base.Portfolio'),
=======
            field=models.ManyToManyField(to='xnote_base.Tag', blank=True),
>>>>>>> origin/master
        ),
        migrations.AddField(
            model_name='follow',
            name='followed',
<<<<<<< HEAD
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers_follow_obj', to='xnote_base.SuperConductor'),
=======
            field=models.ForeignKey(related_name='followers_follow_obj', to='xnote_base.SuperConductor'),
>>>>>>> origin/master
        ),
        migrations.AddField(
            model_name='event',
            name='conductor',
<<<<<<< HEAD
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_list', to='xnote_base.SuperConductor'),
=======
            field=models.ForeignKey(related_name='event_list', to='xnote_base.SuperConductor'),
>>>>>>> origin/master
        ),
        migrations.AddField(
            model_name='event',
            name='places',
            field=models.ManyToManyField(to='xnote_base.Place'),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(to='xnote_base.Tag'),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('superinstitution_ptr', models.OneToOneField(parent_link=True, auto_created=True, primary_key=True, serialize=False, to='xnote_base.SuperInstitution')),
            ],
            bases=('xnote_base.superinstitution',),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('superinstitution_ptr', models.OneToOneField(parent_link=True, auto_created=True, primary_key=True, serialize=False, to='xnote_base.SuperInstitution')),
                ('is_department_group', models.BooleanField(default=False)),
            ],
            bases=('xnote_base.superinstitution',),
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('superinstitution_ptr', models.OneToOneField(parent_link=True, auto_created=True, primary_key=True, serialize=False, to='xnote_base.SuperInstitution')),
            ],
            bases=('xnote_base.superinstitution',),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set([('name',)]),
        ),
        migrations.AddField(
            model_name='superinstitution',
            name='members',
<<<<<<< HEAD
            field=models.ManyToManyField(through='xnote_base.Membership', to='xnote_base.Person'),
=======
            field=models.ManyToManyField(to='xnote_base.Person', through='xnote_base.Membership'),
>>>>>>> origin/master
        ),
        migrations.AddField(
            model_name='studentity',
            name='person',
<<<<<<< HEAD
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xnote_base.Person'),
=======
            field=models.ForeignKey(blank=True, to='xnote_base.Person', null=True),
>>>>>>> origin/master
        ),
        migrations.AddField(
            model_name='person',
            name='follows',
            field=models.ManyToManyField(related_name='followers', through='xnote_base.Follow', to='xnote_base.SuperConductor'),
        ),
        migrations.AddField(
            model_name='person',
            name='interested_tags',
            field=models.ManyToManyField(to='xnote_base.Tag', blank=True),
        ),
        migrations.AddField(
            model_name='person',
            name='user',
<<<<<<< HEAD
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL),
=======
            field=models.OneToOneField(related_name='person', to=settings.AUTH_USER_MODEL),
>>>>>>> origin/master
        ),
        migrations.AddField(
            model_name='membership',
            name='institution',
<<<<<<< HEAD
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_obj', to='xnote_base.SuperInstitution'),
=======
            field=models.ForeignKey(related_name='membership_obj', to='xnote_base.SuperInstitution'),
>>>>>>> origin/master
        ),
        migrations.AddField(
            model_name='membership',
            name='person',
<<<<<<< HEAD
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_obj', to='xnote_base.Person'),
=======
            field=models.ForeignKey(related_name='membership_obj', to='xnote_base.Person'),
>>>>>>> origin/master
        ),
        migrations.AddField(
            model_name='follow',
            name='follower',
<<<<<<< HEAD
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_follow_obj', to='xnote_base.Person'),
=======
            field=models.ForeignKey(related_name='following_follow_obj', to='xnote_base.Person'),
>>>>>>> origin/master
        ),
        migrations.AddField(
            model_name='event',
            name='invited',
            field=models.ManyToManyField(related_name='invite_list', to='xnote_base.Person'),
        ),
        migrations.AddField(
            model_name='studentity',
            name='department',
            field=models.ForeignKey(blank=True, to='xnote_base.Department', null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='related_university',
            field=models.ForeignKey(related_name='xnote_base_group_related', to='xnote_base.University', null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='related_university',
            field=models.ForeignKey(blank=True, to='xnote_base.University', null=True),
        ),
    ]
