# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-29 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xnote_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='related_university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_groups', to='xnote_base.University'),
        ),
    ]
