# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-24 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xnote_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superinstitution',
            name='members',
            field=models.ManyToManyField(to='xnote_base.Person'),
        ),
    ]
