# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-24 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xnote_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superconductor',
            name='real_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
