# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-25 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xnote_base', '0005_auto_20160225_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superinstitution',
            name='is_formal',
        ),
        migrations.AddField(
            model_name='superconductor',
            name='is_formal',
            field=models.BooleanField(default=False),
        ),
    ]
