# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-25 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xnote_base', '0006_auto_20160225_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xnote_base.Event'),
        ),
        migrations.AlterField(
            model_name='post',
            name='related_tags',
            field=models.ManyToManyField(blank=True, null=True, to='xnote_base.Tag'),
        ),
    ]
