# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-25 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xnote_base', '0007_auto_20160225_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='related_tags',
            field=models.ManyToManyField(blank=True, to='xnote_base.Tag'),
        ),
    ]
