# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-26 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xnote_base', '0009_auto_20160226_0323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='superconductor',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image'),
        ),
    ]
