# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-26 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xnote_base', '0010_auto_20160226_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='superconductor',
            name='real_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
