# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-26 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xnote_base', '0011_superconductor_real_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='superconductor',
            name='description',
            field=models.CharField(default='Nothing', max_length=1000),
        ),
    ]
