# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-27 00:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xnote_base', '0013_auto_20160226_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='followed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers_follow_obj', to='xnote_base.SuperConductor'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_follow_obj', to='xnote_base.Person'),
        ),
    ]
