# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-28 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('xnote_base', '0015_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='superinstitution',
            name='members',
            field=models.ManyToManyField(through='xnote_base.Membership', to='xnote_base.Person'),
        ),
        migrations.AddField(
            model_name='membership',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_obj', to='xnote_base.SuperInstitution'),
        ),
        migrations.AddField(
            model_name='membership',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_obj', to='xnote_base.Person'),
        ),
        migrations.AddField(
            model_name='membership',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_obj', to='xnote_base.Portfolio'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='permissions',
            field=models.ManyToManyField(related_name='related_portfolios', to='xnote_base.Permission'),
        ),
    ]
