# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-28 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xnote_base', '0016_auto_20160228_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='portfolio',
        ),
    ]
